### PR TITLE
fix: scrolling when using fullscreen

### PR DESCRIPTION
**Pull request by alfonsobries**
## Summary

Closes https://github.com/ArdentHQ/nova-enhanced-markdown/issues/13
Ticket https://app.clickup.com/t/3kccnnh

## Checklist

-   [ ] I checked my (code) changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by alexbarnsley — CHANGES_REQUESTED** [review]
Fixes the scrolling of the textarea but the page itself has scroll which interferes with it a little. Can the body-scroll-lock be used for that fullscreen modal? :thinking: 

image

**Comment by alfonsobries** [comment]
@alexbarnsley can you please try again?

**Comment by ItsANameToo** [comment]
@alfonsobries @alexbarnsley I'm unable to scroll the content with this last change. There's only a single scrollbar now, but that seems to be scrolling something else and not the markdown content. Sent video in slack

**Comment by ItsANameToo** [comment]
works now, apparently browser cache was acting up.

@alfonsobries some conflicts due to the merge of the other feature + scrollbar does not seem to be on the edge of the view (it's slightly to the left of where you'd expect it). Is that something we can adjust?
image

**Comment by ItsANameToo** [comment]
alex also ran into this on linux, might be similar on windows as well

image (7)

**Comment by alfonsobries** [comment]
@ItsANameToo @alexbarnsley adjusted the style, tested on windows + edge, and ubuntu + firefox should be ok now

**Review by alexbarnsley — APPROVED** [review]

**Pull request merged**
